### ISSUE TITLE
Test Crime Section for Broken Links

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#27]
The website is now available for testing. Please click through the History section of website and make a list of all of the broken links. This includes all the links in the sidebar and every link contained within a page that is linked from the sidebar.

Section URL: http://homicide.northwestern.edu.s3-website-us-east-1.amazonaws.com/crimes/

### Done Looks Like

- Create a word document or spreadsheet with a list of broken links. We need the URL where the broken link exists and a brief description (i.e. is it supposed to be an image, another page, an external website, etc.)
- Add a comment to this issue that includes a file attachment containing the list of broken links. If the entire section works as expected, close the issue.

**Comment by ashleyahn** [comment]
[Broken Links - Crime.docx](https://github.com/nulib/homicide-in-chicago/files/3082766/Broken.Links.-.Crime.docx)
