### ISSUE TITLE
Capital Punishment cases

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#38]
File: `/content/legal/capital-cases.md`

Please change the Markdown formatting for this page to make it more readable. This page is a list of case summaries, case numbers, and links to the case record. Each of them is preceeded by a Date in **bold** heading.

Each case summary should follow this pattern:
```
**Date**

- Case Description
- Case number
- [Link](/to/case_number/)
```

Here's an example:
```
**July 27, 1919**

- Wilkinson, Jannet - Age 6 - Choked to death and body hidden under coal in basement of 114 E. Superior St., by Thomas Fitzgerald, who, on July 28 was held by the Coroner. 28 Pct. 9/23/19 - Sentenced to hang 10/17/19 - Crowe. 10/17/19 - Hanged at County Jail.
- Case number: 5558
- [View case details](/database/5419/)
```

I started doing this for the first four cases mentioned on the page. Please finish this file.

### Done looks like
- a PR is submitted to update this file

_be sure to add a link to this issue in the PR_

**Comment by echoe320** [comment]
fixed in #40
