### ISSUE TITLE
Organize PDFs that are Missing from LAW section

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#41]
Consult this document: https://northwestern.box.com/s/dw4dcau3wads01mee2b7uwewpipr6k4u 

For every broken link that appears to be related to a missing PDF file...

- Visit homicide.northwestern.edu
- Download the original file (don't change the file name)
- Save that file to a folder that matches the URL path (e.g. `/doc_fk/homicide/`)
- Upload the files to box: https://northwestern.box.com/s/916nd7jjzvjex960xh32skysl3wtlwje

### Done looks like
- Files are in box
- Notes about this work is submitted as a comment to this issue
- This issue is closed

**Comment by echoe320** [comment]
Solved in #47

all pdf links are solved
