### ISSUE TITLE
Organize PDFs that are Missing from HISTORY section

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#42]
Consult this document: https://northwestern.box.com/s/gksn7m504fhaqe2zjsrgd5cxl8o5lf7j

For every broken link that appears to be related to a missing PDF file...

- Visit homicide.northwestern.edu
- Download the original file (don't change the file name)
- Save that file to a folder that matches the URL path (e.g. `/doc_fk/homicide/`)
- Upload the files to box: https://northwestern.box.com/s/916nd7jjzvjex960xh32skysl3wtlwje

### Done looks like
- Files are in box
- Notes about this work is submitted as a comment to this issue
- This issue is closed

**Comment by echoe320** [comment]
Only Jane Addams and Hull House page has broken links. All other PDF links are solved.

fixed in #47
