### ISSUE TITLE
Organize PDFs that are Missing from CRIME section

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#43]
Consult this document: https://northwestern.box.com/s/kry41gy0028iq0trv3h36va4k57kmk7n

For every broken link that appears to be related to a missing PDF file...

- Visit homicide.northwestern.edu
- Download the original file (don't change the file name)
- Save that file to a folder that matches the URL path (e.g. `/doc_fk/homicide/`)
- Upload the files to box: https://northwestern.box.com/s/916nd7jjzvjex960xh32skysl3wtlwje

### Done looks like
- Files are in box
- Notes about this work is submitted as a comment to this issue
- This issue is closed

**Comment by echoe320** [comment]
Only 1870: Harrison Street Police Station page has broken links. All other PDF links are solved.

fixed in #47
