### ISSUE TITLE
Images on Anti-Corruption Campaigns

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#45]
Anti-Corruption campaigns has some display issues: http://homicide.northwestern.edu.s3-website-us-east-1.amazonaws.com/legal/corruption/ 

Consider converting the [Bulma Tiles](https://bulma.io/documentation/layout/tiles/) markup to [Bulma columns](https://bulma.io/documentation/columns/basics/).

The result would be a columns `div` containing two columns with one image in each column, followed by a markdown formatted paragraph until the page is finished. The layout would look something like:

- Bulma columns HTML for images
- Markdown paragraph
- Bulma columns HTML for images
- Markdown paragraph
- Bulma columns HTML for images
- Markdown paragraphs

**Comment by chrisdaaz** [comment]
Use tiles or columns. An example of a working file is in `/content/legal/cpd/_index.md`

**Comment by echoe320** [comment]
completed in #53
