### ISSUE TITLE
Convert Bibliography Entries into List Items

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#48]
The [Bibliography](http://homicide.northwestern.edu.s3-website-us-east-1.amazonaws.com/about/bibliography/) is difficult to skim. We can improve the readability of the page by making turning the entries into list items in Markdown. 

This is the file that needs editing: `/content/about/bibliography.md`

The resulting file should look something like:

```

### Section Title
- Bib entry
- Bib entry
- Bib entry

### Section Title
- Bib entry
- Bib entry
- Bib entry

```

You can do this by simply adding a `-` at the beginning of each entry to turn it into a markdown list item. Other suggestions for improving the readability of the page are welcome.

**Comment by echoe320** [comment]
solved in #54
