### ISSUE TITLE
Improve Readability of  "Links to Related Sites" page

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#49]
The [Links to Related Sites](http://homicide.northwestern.edu.s3-website-us-east-1.amazonaws.com/about/links/) page is difficult to skim. We can improve the readability of the page by making turning the entries into list items in Markdown. 

This is the file that needs editing: `/content/about/links.md`

The resulting file should look something like:

```

### Section Title
- Bib entry
- Bib entry
- Bib entry

### Section Title
- Bib entry
- Bib entry
- Bib entry

```

You can do this by simply adding a `-` at the beginning of each entry to turn it into a markdown list item. Other suggestions for improving the readability of the page are welcome.

**Comment by echoe320** [comment]
solved in #54
