### ISSUE TITLE
Timeline Markdown Files

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/homicide-in-chicago#9]
### Description

For every year in the [timeline](http://homicide.northwestern.edu/historical/timeline/), there is an index page that lists images from that year.

For example, the index page for 1872 contains six images: http://homicide.northwestern.edu/historical/timeline/1871/ 

![image](https://user-images.githubusercontent.com/24395592/54160576-ee0bc580-441d-11e9-936a-113f04160c92.png)

Each image has it's own page that contains information about the image. For example, 
http://homicide.northwestern.edu/historical/timeline/1871/216/

![image](https://user-images.githubusercontent.com/24395592/54160638-185d8300-441e-11e9-84c7-235d9e28757f.png)

We need markdown files for every year's index page, and every image added to the `/content/historical/timeline/` directory.

### Content structure

- In the `/historical/timeline` directory, create a folder and title it the year that it will represent (e.g. `/timeline/1872`.
- Create an `_index.md` file in each year's folder to represent the year's index page.
- For every image from that year, create a markdown file using the number of the image from the original URL (e.g. the markdown file for [this image](http://homicide.northwestern.edu/historical/timeline/1871/216/) will be called `216.md` and it will live in the `/1871` folder of the `/content/historical/timeline/` directory

### Markdown contents

**Image Front-matter: **

```
---
title: "[Title of the Photo]"
year: [YEAR]
layout: timeline
---
```

**Index Page Front-matter: **

```
---
title: "Timeline of the City's History: [YEAR]"
layout: timeline
---
```

**Markdown for images**

Instead of using markdown form images, we are using shortcodes that follow this structure:

```
{{< image title="[TITLE OF THE IMAGE" src="/img/timeline/[YEAR]/large/[Markdown Filename]" >}}

```

Here's an example:

```
{{< image title="The Livestock Pavilion at Halsted and 42nd Streets" src="/img/timeline/1872/large/245.jpg" >}}
```

**Comment by chrisdaaz** [comment]
was this completed in #11 @echoe320

**Comment by echoe320** [comment]
No, I still need to complete it. Will do so on Friday.
